# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


# Title of my site
title: Victor Liem
# Website URL
baseurl: "victorliem.netlify.app"
# Copyright text in footer
copyright: '© Victor Liem {year} · Powered by [blogdown](https://bookdown.org/yihui/blogdown/) and the [Acacemic theme](https://wowchemy.com/) for [Hugo](https://gohugo.io/)' 

############################
## MODULES
############################
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy

##==================##
## Advanced setting ##  
##==================##

# Name of Academic theme folder in `themes/`.
theme: "starter-academic"

# Get last modified date for content from Git?
enableGitInfo: false

# Default language if multilanguage
defaultContentLanguage: "en"
hasCJKLanguage: false # true for japanese/korean/chinese
defaultContentLanguageInSubdir: false
removePathAccents: true

# Summary length in words
summaryLength: 30
# No of items per page
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true # Enable user to embed HTML snippets in Markdown content.
  highlight:
    codeFences: false # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  tableOfContents:
    startLevel: 2
    endLevel: 3
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart # Anchor for cropping. Options include Smart and Center.
timeout: 600000
# Taxonomies
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70